### PR TITLE
Rebase of call-method against current master

### PR DESCRIPTION
**Pull request by murrayrm**
@sawyerbfuller Here's an attempt at a rebase of this PR against the current master.

@bnavigator You might want to scan this to make sure I didn't drop something from one of your merged PR's.

### CODE REVIEW

**Comment by sawyerbfuller** [comment]
looking thrugh it now. anything in particular you remember as needng attention/merge conflicts? also: wont be able to run pytest on this - does it pass tests? (hurt my hand so wont be coding for a few weeks)

**Comment by murrayrm** [comment]
This passes all the [unit tests](https://travis-ci.org/github/murrayrm/python-control/builds/753134711).

There were some fairly substantial changes in `margins.py` that it would be good to check.  I think the rest of it was pretty straightforward.

**Comment by sawyerbfuller** [comment]
i see them now, from @bnavigator's updates for DT margin calculations. They look good to me. 

how do you want to do this? should merge this pull request?

**Comment by murrayrm** [comment]
If everything looks OK to you, you can merge this PR into your repository, which should automatically map things over to the PR on `python-control/python-control`.  From there, we can confirm that unit tests work and then merge that PR into the master branch.

**Comment by bnavigator** [comment]
Careful! The base branch of this PR is sawyerbfuller:master not the branch for python-control/python-control#449 
 sawyerbfuller:call-method

(I did not have time yet to review.)

The diff here does not display the real change but all the differences between past and current master. Should be possible to compare 195bec3effa50052518ebf4cd042c846eecdd964 vs https://github.com/python-control/python-control/pull/449/files for review (will do it later today) and then either merge into  sawyerbfuller:call-method (which will create some convoluted tree lines in the git history) or reset sawyerbfuller:call-method to 195bec3effa50052518ebf4cd042c846eecdd964 (which will lose the commit history)

**Comment by murrayrm** [comment]
Oops.  Sorry about that!  I'm going to kill this PR and regenerate one that uses the correct branch.

**Comment by bnavigator** [comment]
You can edit the base branch

**Comment by bnavigator** [comment]
There are quite a few `evalfr()` calls left in margins.py, which might have been introduced between the inception if this PR and now.

**Comment by bnavigator** [comment]
Review comments in python-control/python-control#499

**Pull request closed without merging**
